### PR TITLE
(#2138081) More post v252 fixes for issues/regressions

### PR DESCRIPTION
**Pull request by mrc0mmand**
Includes (among others) https://github.com/systemd/systemd/pull/25222 and https://github.com/systemd/systemd/pull/25541.

### CODE REVIEW

**Review by jamacku — COMMENTED** [review]
We should also include:
- https://github.com/systemd/systemd/pull/25580

**Comment by mrc0mmand** [comment]
> We should also include:
> 
>     * [systemd/systemd#25580](https://github.com/systemd/systemd/pull/25580)

Indeed, backported + one additional patch for quite an old regression.

**Review by dtardon — APPROVED** [review]
I know zilch about EFI, hence I cannot say anything about the sd-boot changes. Let's just trust upstream that they make sense.

LGTM otherwise.

**Comment by mrc0mmand** [comment]
Another force push, since 73d88b806b92efa0738bb6bcccbf105441f6d8cb doesn't apply cleanly without a huge amount of other dissect patches I really don't want to backport. The conflict is, thankfully, pretty simple, e.g.:

```diff
diff --cc src/shared/dissect-image.c                                                                                                                                                                                  
index 7676636723,9ce9775049..0000000000                                                                                                                                                                               
--- a/src/shared/dissect-image.c                                                                           
+++ b/src/shared/dissect-image.c                                                              
@@@ -433,10 -454,11 +433,10 @@@ static int dissect_image                                                                                                                                                              
                  (void) blkid_probe_lookup_value(b, "USAGE", &usage, NULL);        
                  if (STRPTR_IN_SET(usage, "filesystem", "crypto")) {                                      
                          _cleanup_free_ char *t = NULL, *n = NULL, *o = NULL;                   
 -                        const char *fstype = NULL, *options = NULL, *suuid = NULL;
 +                        const char *fstype = NULL, *options = NULL;                                                                                                                                                 
                          _cleanup_close_ int mount_node_fd = -1;                                          
 -                        sd_id128_t uuid = SD_ID128_NULL;                             
                                                                                               
-                         if (FLAGS_SET(flags, DISSECT_IMAGE_OPEN_PARTITION_DEVICES)) {                    
+                         if (FLAGS_SET(flags, DISSECT_IMAGE_PIN_PARTITION_DEVICES)) {                     
                                  mount_node_fd = open_partition(devname, /* is_partition = */ false, m->loop);                                                                                                       
                                  if (mount_node_fd < 0)                                                                                                                                                              
                                          return mount_node_fd;                                                                                                                                                       
@@@ -864,14 -860,18 +864,19 @@@                                                                                                                                                                                       
                                           * let the newest version win. This permits a simple A/B versioning                                                                                                         
                                           * scheme in OS images. */                          
                                                                           
 -                                        if (compare_arch(type.arch, m->partitions[type.designator].architecture) <= 0)                                                                                              
 -                                                continue;                                                                                                                                                           
 -                                                                                                                                                                                                                                                                                                                                                                                                                                           
 -                                        if (!partition_designator_is_versioned(type.designator) ||
 -                                            strverscmp_improved(m->partitions[type.designator].label, label) >= 0)
 +                                        if (!PARTITION_DESIGNATOR_VERSIONED(designator) ||
 +                                            strverscmp_improved(m->partitions[designator].label, label) >= 0)
                                                  continue;
   
 -                                        dissected_partition_done(m->partitions + type.designator);
 +                                        dissected_partition_done(m->partitions + designator);
                                  }
   
++<<<<<<< HEAD
 +                                if (FLAGS_SET(flags, DISSECT_IMAGE_OPEN_PARTITION_DEVICES)) {
++=======
+                                 if (FLAGS_SET(flags, DISSECT_IMAGE_PIN_PARTITION_DEVICES) &&
+                                     type.designator != PARTITION_SWAP) {
++>>>>>>> 73d88b806b (dissect: rework DISSECT_IMAGE_ADD_PARTITION_DEVICES + DISSECT_IMAGE_OPEN_PARTITION_DEVICES)
                                          mount_node_fd = open_partition(node, /* is_partition = */ true, m->loop);
                                          if (mount_node_fd < 0)
                                                  return mount_node_fd;
```

since the `type.designator` stuff was introduced by https://github.com/systemd/systemd/pull/25001 which then depends on other dissect PRs.

**Review by msekletar — APPROVED** [review]
LGTM

**Pull request merged**
