### PR TITLE
(RHEL-13199) Backport ukify from systemd-255-rc2

### PR DESCRIPTION
**Pull request by keszybz**
This is just the first piece. I'm starting with this to let the CI run. We would also need to update the spec file to use the new option, and figure out how to deal with the `pefile` dependency. But I think this should be handled in the `dist-git` repo.

All the tests pass on Fedora 39.

### CODE REVIEW

**Comment by keszybz** [comment]
I didn't include the patch that moves `ukify` to `/usr/bin/`… Do we want that here?

**Comment by jamacku** [comment]
@msekletar I think that this two commits are an exception. It would be impossible to bacport individual commits a reference them correctly. In the same time these commits aren't, a rhel-only because that would indicate that we want to keep them I case of rebase. 

I think it's fine to leave them as they are.

**Comment by jamacku** [comment]
Maybe we should have some label for this case like we have the rhel-only label. On the other hand we don't have this situation often.

**Comment by msekletar** [comment]
@jamacku Fine by me then.

**Pull request merged**
