### PR TITLE
(#2031426) man: do not install sd-boot man pages when -Dgnu-efi=false is set

### PR DESCRIPTION
**Pull request by davide125**
https://bugzilla.redhat.com/show_bug.cgi?id=2031426

https://github.com/systemd/systemd/commit/34357545590d4791d1acbbeb07ae8f7636e187cb gated sd-boot on -Dgnu-efi=false, but right now the manpages are still installed when that is set, even though the corresponding binaries are not. Update the gating to solve this.

This is a cherrypick of https://github.com/systemd/systemd/commit/ba38a24de3e15cb32450c397cf2eac951e75fb03

Related GitLab MR: https://gitlab.com/redhat/centos-stream/rpms/systemd/-/merge_requests/39

### CODE REVIEW

**Review by Conan-Kudo — DISMISSED** [review]

**Review by jamacku — COMMENTED** [review]
@davide125 Could you please add to commit message:
```
Resolves: #2031426
```

**Comment by davide125** [comment]
@jamacku Done, thanks!

**Review by jamacku — APPROVED** [review]
Thank you, LGTM

**Review by Conan-Kudo — APPROVED** [review]

**Comment by jamacku** [comment]
@mrc0mmand Could you please have a look at CentOS CI? Thank you.

**Comment by mrc0mmand** [comment]
The CI fails are unrelated, but it's a real issue (I've already discussed this with @dtardon yesterday).

**Comment by jamacku** [comment]
> The CI fails are unrelated, but it's a real issue (I've already discussed this with @dtardon yesterday).

Ohh, do we have an issue for it?

**Comment by mrc0mmand** [comment]
> > The CI fails are unrelated, but it's a real issue (I've already discussed this with @dtardon yesterday).
> 
> Ohh, do we have an issue for it?

We do now: https://github.com/redhat-plumbers/systemd-rhel9/issues/55.

**Pull request merged**
