### PR TITLE
(#2160477) Assorted fixes for mm bugs in unit management

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Review by jamacku — CHANGES_REQUESTED** [review]
@msekletar Please add a `cherry-picked from commit <xyz>` annotation to all commits. Also, commit [e586ad2](https://github.com/redhat-plumbers/systemd-rhel9/pull/131/commits/e586ad24a0864358ab95d33902113d1456e9af6c) is missing Bugzilla reference. Thank you.

**Comment by msekletar** [comment]
@jamacku this wasn't ready for the review, but I forgot to mark it as a draft. Thanks for the review anyway.

**Comment by msekletar** [comment]
@mrc0mmand any idea about the CI failure?

**Comment by mrc0mmand** [comment]
> @mrc0mmand any idea about the CI failure?

I just opened https://github.com/systemd/systemd/pull/26040 which should fix it. As for the "base" C9S job - just ignore it for now, I'll do some debugging tomorrow.

**Review by dtardon — DISMISSED** [review]
LGTM

**Comment by mrc0mmand** [comment]
> @mrc0mmand any idea about the CI failure?

I backported two test-only commits for TEST-26 and fixed (worked around) an issue in the regular C8S job, so now everything should pass again.

**Review by jamacku — APPROVED** [review]
LGTM

**Pull request merged**
