### PR TITLE
(#2190226) Support defining mount units on the kernel command line

### PR DESCRIPTION
**Pull request by dtardon**
Resolves: #2190226

### CODE REVIEW

**Comment by msekletar** [comment]
@dtardon it seems to me that issues reported by GH code scanning are valid. Fixing them before we merge this would be nice.

**Comment by msekletar** [comment]
Also CI is unhappy, failures seem unrelated though. @dtardon can you please retrigger it?

**Comment by dtardon** [comment]
> @dtardon it seems to me that issues reported by GH code scanning are valid. Fixing them before we merge this would be nice.

Yes, they are. But it's what upstream has done and it makes the checks consistent, as they all use the same pattern.

**Comment by msekletar** [comment]
@dtardon can you please investigate CI failures? They seem to be related ...

**Comment by dtardon** [comment]
> @dtardon can you please investigate CI failures? They seem to be related ...

They were. And I've added another 4 commits to already large enough PR...

**Review by msekletar — APPROVED** [review]
LGTM

**Pull request merged**
