### PR TITLE
(#2013213) core: decrease log level of messages about use of KillMode=none

### PR DESCRIPTION
**Pull request by msekletar**
RHEL-only

Resolves: #2013213

### CODE REVIEW

**Comment by jamacku** [comment]
@msekletar to fix ci, we need https://github.com/systemd/systemd/pull/22597

**Review by jamacku — COMMENTED** [review]
LGTM

**Comment by jamacku** [comment]
@mrc0mmand could you please review CI changes, thanks.

**Review by mrc0mmand — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
