### PR TITLE
(#2087652) ci: limit which env variables we pass through `sudo`

### PR DESCRIPTION
**Pull request by dtardon**
to work around #23987.

(cherry picked from commit d46e7c7cfd6c286a38298c067f16ac784c2a26f0)

Related: #2087652

### CODE REVIEW

**Comment by mrc0mmand** [comment]
@dtardon could you, please, backport https://github.com/systemd/systemd/pull/23099 as well, since without it dfuzzer keeps crashing systemd? When at it, it might also be a good idea to backport https://github.com/systemd/systemd/pull/23283 too.

**Comment by mrc0mmand** [comment]
> @dtardon could you, please, backport [systemd/systemd#23099](https://github.com/systemd/systemd/pull/23099) as well, since without it dfuzzer keeps crashing systemd? When at it, it might also be a good idea to backport [systemd/systemd#23283](https://github.com/systemd/systemd/pull/23283) too.

I mean, it doesn't have to be in this PR specifically, it's just an explanation why the sanitizer run keeps failing (in this and other PRs). I might also be worth going through the dfuzzer-related issues and backport the respective fixes, if deemed useful (https://github.com/systemd/systemd/issues?q=dfuzzer).

**Review by msekletar — APPROVED** [review]
LGTM

**Comment by mrc0mmand** [comment]
@Mergifyio refresh

**Pull request merged**
