### PR TITLE
(RHEL-11591) Avoid SIGBUS during journal file rotation

### PR DESCRIPTION
**Pull request by dtardon**
Resolves: RHEL-11591

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Is the issue reference here correct? Since https://issues.redhat.com/browse/RHEL-11591 is for RHEL 9.2, but this PR is opened against current main.

**Comment by mrc0mmand** [comment]
> Is the issue reference here correct? Since https://issues.redhat.com/browse/RHEL-11591 is for RHEL 9.2, but this PR is opened against current main.

I'm an idiot, nevermind, looked at the wrong field :)

**Review by mrc0mmand — APPROVED** [review]
LGTM.

**Comment by jamacku** [comment]
> > Is the issue reference here correct? Since https://issues.redhat.com/browse/RHEL-11591 is for RHEL 9.2, but this PR is opened against current main.
> 
> I'm an idiot, nevermind, looked at the wrong field :)

No :) This should be improved. The text is confusing, but it's partially due to JIRA because it doesn't have a field that would tell you what major version of RHEL is affected. :(

**Pull request merged**
