### PR TITLE
(#2239440) (#2239576) rules: fix CPU hotplug on IBM platforms

### PR DESCRIPTION
**Pull request by bmasonrh**
This PR combines two interrelated cherry-picked commits:
- [rules: do not online CPU automatically on IBM platforms](https://github.com/redhat-plumbers/systemd-rhel9/commit/94c7e260b499cd9e5ad8d99d95b9413df2d50cc6)
- [rules: online CPU automatically on IBM s390x platforms when configured](https://github.com/redhat-plumbers/systemd-rhel9/commit/65d993c2efe52d683396dc3181cc79f29698bf39)

To resolve the following bugs in 9.0.0-z EUS:
- [BZ 2239440](https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2239440) cloned from [BZ 2143107](https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2143107)
- [BZ 2239576](https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2239576) cloned from [BZ 2212612](https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2212612)

### CODE REVIEW

**Review by jamacku — CHANGES_REQUESTED** [review]
Could you please split this change into two PRs? We are used to having one bug per PR. Also, our automation is expecting one bug/issue per PR. Thank you.

**Comment by bmasonrh** [comment]
> Could you please split this change into two PRs? We are used to having one bug per PR. Also, our automation is expecting one bug/issue per PR. Thank you.

I'm not sure that I can split this into two separate PRs.  The second commit ([c3df122](https://github.com/redhat-plumbers/systemd-rhel9/commit/c3df1221b77295fe58ede875aaa8b7646c27a547)) can't be applied until after the first commit ([4115194](https://github.com/redhat-plumbers/systemd-rhel9/commit/4115194daf78509d881a87d5412078d519772f27)) is applied.

The first commit caused a regression that was fixed by the second commit.  The second commit patches the same part of the file that was patched by the first commit.

I can't apply the second commit on top of the base rhel-9.0.0 branch -- the only way to apply the second commit is on top of the first commit.  I created two branches from my rhel-9.0.0 fork:

```
bz2239576-online-s390x-cpu (with second commit cherry-picked from 65d993c)
    ^
    |
bz2239440-online-ibm-cpu   (with first  commit cherry-picked from 94c7e26)
    ^
    |
rhel-9.0.0
```

and then created a [draft PR](https://github.com/redhat-plumbers/systemd-rhel9/pull/200) from the [bz2239440-online-ibm-cpu](https://github.com/bmasonrh/systemd-rhel9/tree/bz2239440-online-ibm-cpu) without a problem; but when I tried to create a PR from [bz2239576-online-s390x-cpu](https://github.com/bmasonrh/systemd-rhel9/tree/bz2239576-online-s390x-cpu), it of course included both commits in the PR.

I could amend this PR to reference only one of the Bugs (probably the newer one) and then add a note to the other BZ that it was resolved with this PR.  Or I could create a PR with the first patch, wait for it to be merged, and then create a PR with the second patch. Or maybe there's another way -- I apologize if I've missed something.  Please let me know how you'd like to proceed.

**Comment by mrc0mmand** [comment]
Could you cherry pick https://github.com/systemd/systemd/commit/bbe53713455be38c0a587626439fd171f28c77fc as well? It should make the CIs a bit less *angry*.

**Comment by jamacku** [comment]
> I could amend this PR to reference only one of the Bugs (probably the newer one) and then add a note to the other BZ that it was resolved with this PR. Or I could create a PR with the first patch, wait for it to be merged, and then create a PR with the second patch. Or maybe there's another way -- I apologize if I've missed something. Please let me know how you'd like to proceed.

You are right, so in that case, I would either:
- close https://bugzilla.redhat.com/show_bug.cgi?id=2239576 as a duplicate of https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2239440 and then commit both commits under #2239576
- or I would create two PRs where the first would contain the first commit, and the second PR would be based on the first PR and would also have the second commit. Once we merge the first PR and you rebase the second one, it should contain only one commit.

What you find easier or more straightforward is up to you. Feel free to ping me if you have any questions.

**Comment by bmasonrh** [comment]
I've submitted a PR #200 for the first patch (and also systemd/systemd@bbe5371 requested by mrc0mmand.  Once that's merged I'll submit a second PR for the second patch.

**Pull request closed without merging**
