### PR TITLE
(#1972223) boot: don't build bootctl when -Dgnu-efi=false is set

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by dtardon** [comment]
This needs https://github.com/systemd/systemd/pull/20791 too, doesn't it?

**Comment by dtardon** [comment]
> This needs [systemd/systemd#20791](https://github.com/systemd/systemd/pull/20791) too, doesn't it?

No, it doesn't.

**Review by dtardon — APPROVED** [review]
LGTM

**Comment by msekletar** [comment]
We force-pushed `main` branch and reset it back to f583f3d. Commits from this PR were deleted, hence I've resubmitted relevant changes as #39.

**Pull request merged**
