### PR TITLE
(#1960703) ci: initial CI configuration

### PR DESCRIPTION
**Pull request by mrc0mmand**
* CIFuzz would need a separate project in oss-fuzz
  * Coverity would also need a separate project
  * the Labeler action is superfluous, since we already have a bot for
    that
  * mkosi testing on other distros is irrelevant for downstream RHEL
    repo

Resolves: #TBD
rhel-only

---

TODO:
  - [x] drop irrelevant CI configs
  - [ ] introduce a CentOS-based CI like we have for the RHEL 8 repo (with CentOS 8 docker/podman images for now)
  - [x] configure Packit (epel-9-* chroots, not yet available)
    * spec: https://gitlab.com/redhat/centos-stream/rpms/systemd/-/blob/c9s/systemd.spec
  - [x] set up CentOS CI for this repo (CentOS 9 not yet available)

### CODE REVIEW

**Comment by mrc0mmand** [comment]
I configured LGTM and CentOS CI for this repo (so far it runs on CentOS 8 + some [custom built dependencies](https://copr.fedorainfracloud.org/coprs/mrc0mmand/systemd-centos-ci-centos8/) I already use for the upstream run). The GH actions provide unit tests coverage (w/ and w/o ASan and UBSan) and build coverage across multiple compilers and versions.

Once there are some public CentOS 9 images available, I'll configure Packit (and the related machinery).

PTAL!

**Comment by msekletar** [comment]
This needs rebasing since we force pushed the `main` branch with systemd-249. @mrc0mmand PTAL.

**Comment by mrc0mmand** [comment]
@msekletar rebased

**Review by msekletar — APPROVED** [review]
LGTM

**Pull request merged**
