### PR TITLE
(RHEL-5988) Assign alternative names only on add uevent

### PR DESCRIPTION
**Pull request by dtardon**

### CODE REVIEW

**Comment by msekletar** [comment]
@dtardon CI failures looks legitimate.

**Comment by lnykryn** [comment]
The shellcheck failure is a false positive. https://github.com/koalaman/shellcheck/wiki/SC2317#exceptions

**Review by jamacku — DISMISSED** [review]
@dtardon, the original bug was migrated to JIRA, so, unfortunately, we have to reference instead:

https://issues.redhat.com/browse/RHEL-5988

**Review by msekletar — APPROVED** [review]
LGTM

**Comment by mrc0mmand** [comment]
The test introduced in this PR actually fails (as pointed out by the CI), and it causes the CI to fail in other PRs as well (https://github.com/redhat-plumbers/systemd-rhel9/pull/215#issuecomment-1847886782).

**Comment by mrc0mmand** [comment]
Ah, found the missing commits, will prep a PR shortly.

**Comment by mrc0mmand** [comment]
-> https://github.com/redhat-plumbers/systemd-rhel9/pull/216

**Pull request merged**
