### PR TITLE
(#2000927) units: don't enable tmp.mount statically in local-fs.target

### PR DESCRIPTION
**Pull request by msekletar**
Related: #2000927

### CODE REVIEW

**Comment by dtardon** [comment]
The 9.0.0 bug is https://bugzilla.redhat.com/show_bug.cgi?id=2000927 . I'm not sure the dist-git check will allow this to be pushed with the 9.0-beta bug reference...

**Comment by dtardon** [comment]
> The 9.0.0 bug is https://bugzilla.redhat.com/show_bug.cgi?id=2000927 . I'm not sure the dist-git check will allow this to be pushed with the 9.0-beta bug reference...

Looking at gitbz code, it looks like it will, as gitbz goes through Blocks list of the referenced bug if the bug itself doesn't have correct release.

**Review by dtardon — APPROVED** [review]
LGTM

**Comment by msekletar** [comment]
I will open new PR and fix the bug reference in commit message.

**Comment by msekletar** [comment]
Closed in favor of #35.

**Pull request closed without merging**
